---
- name: Configure bashrc
  template:
    src: bash.bashrc.j2
    dest: "{{ desktop_user_vars.dir }}/.bashrc"
- name: Configure bash_profile
  copy:
    src: bash_profile
    dest: "{{ desktop_user_vars.dir }}/.bash_profile"
- name: Configure aliases
  template:
    src: bash.aliases.j2
    dest: "{{ desktop_user_vars.dir }}/.bash.aliases"
- name: Install z tool to local home directory
  git:
    clone: yes
    repo: "https://github.com/rupa/z.git"
    update: yes
    dest: "{{ desktop_user_vars.dir }}/.local/z"
  when: limited_internet is not defined
- name: Create bin directory
  file:
    state: directory
    path: "{{ desktop_user_vars.dir }}/.local/bin"
- name: Get downloadable bash bins
  get_url:
    url: "{{ item.value.url }}"
    checksum: "{{ item.value.checksum }}"
    dest: "{{ desktop_user_vars.dir }}/.local/bin/{{ item.key }}"
    mode: "0555"
  loop: "{{ bash_remote_bins | dict2items }}"
- name: Copy bash scripts
  copy:
    content: "{{ item.value }}"
    dest: "{{ desktop_user_vars.dir }}/.local/bin/{{ item.key }}"
    mode: "0555"
  loop: "{{ bash_inline_bins | dict2items }}"
- name: Link bash scripts
  file:
    state: link
    src: "{{ desktop_user_vars.dir ~ '/' ~ item.link_relative_to_home if item.link_relative_to_home is defined else item.link }}"
    path: "{{ desktop_user_vars.dir }}/.local/bin/{{ item.name }}"
    mode: "0555"
    force: yes
  loop: "{{ bash_symlinks }}"
  when: "bash_symlinks is defined"
- name: Setup bash completion commands
  include_tasks: completion_cmd.yml
  loop: "{{ bash_generated_bins | dict2items }}"
